# Generated by Django 6.0.3 on 2026-03-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The base URL of the target', unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(help_text="e.g., 'full', 'recon', 'vuln'", max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.scantarget')),
            ],
        ),
        migrations.CreateModel(
            name='ReconData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of detected technologies')),
                ('dns_records', models.JSONField(blank=True, default=dict, help_text='DNS resolution data')),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recon_data', to='scanner.scantarget')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Vulnerability Name (e.g., 'SQL Injection')", max_length=255)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='INFO', max_length=10)),
                ('endpoint', models.URLField(help_text='The affected URL/Endpoint', max_length=1024)),
                ('parameter', models.CharField(blank=True, help_text='Vulnerable parameter if applicable', max_length=255, null=True)),
                ('proof_of_concept', models.TextField(blank=True, help_text='Payload or response snippet', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scanresult')),
            ],
        ),
    ]
